### ISSUE TITLE
Colocated role port collision check fails for same port with TCP/UDP

### ISSUE THREAD

**Issue by HeavyWombat** [SUSE/fissile#364]
With PR #340, a collision check for colocated roles has been introduced that has an issue when you specify the same port number with different protocols, because the collision check only checks the port number.

```yaml
- name: consul
  colocated_containers:
  - logs-forwarder
  run:
    exposed-ports:
    - name: serf-tcp
      extenral: 8301
      internal: 8301
      protocol: TCP
    - name: serf-udp
      extenral: 8301
      internal: 8301
      protocol: UDP
```

The configuration is totally fine, but the collision checks reports that as an issue: `Error loading roles manifest: role[consul]: Invalid value: 8301: port collision, the same port is used by: consul, consul`

To resolve this, the combination of protocol and port has to be checked against one another, for example: `TCP-8301` and `UDP-8301`. I will start to work on a fix for this as soon as possible.
