### ISSUE TITLE
Create one Kubernetes Service per job

### ISSUE THREAD

**Issue by viovanov** [SUSE/fissile#367]
- [ ] Change helm charts so they generate one service per job
- [ ] Remove the `headless` tag from fissile
- [ ] Exposed ports have to be moved to the job section
- [ ] Update fissile [doc](https://github.com/SUSE/fissile/wiki/Pod-Management-using-Role-Manifest-Tags) 
- [ ] Update SCF/UAA

Use the following rule to determine the service name (which in turn determines the hostname):

```
<role-name>-<job-name>
```

Ports must be exposed like this:

```
roles:
- name: nats
  jobs:
  - name: nats
    properties:
      bosh_containerization:
        ports:
        - name: nats
          protocol: TCP
          internal: 4222
        - name: nats-routes
          protocol: TCP
          internal: 4223
```

**Comment by alexjh** [comment]
> Remove the headless tag from fissile

Can you elaborate on why this is happening?

It looks like we could create up to three services per role right now:

https://github.com/SUSE/fissile/blob/711088fd60db22ace2ad33bd887c91e6f8d4df51/kube/service.go#L16-L36

If the headless tag goes away, does that mean we'll *always* create three services for each StatefulSet, since the `headless` tag would never be set?

**Comment by alexjh** [comment]
Also, it looks like we could determine if a service should be public or not with the `public: true` setting in the port config.

https://github.com/SUSE/scf/blob/b3be225282389bdce24dec05e351f6b697fe5d89/container-host-files/etc/scf/config/role-manifest.yml#L487-L490

**Comment by alexjh** [comment]
Right now in our helm templates we have a StatefulSet per role, and that is linked to service via a `serviceName` called `<role-name>-set`.

```
spec: 
  podManagementPolicy: "OrderedReady"
  replicas: {{ if and .Values.config.HA (eq (int .Values.sizing.api.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.api.count }} {{- end }}
  serviceName: "api-set"
```

I don't see a way to link the newly named service `<role-name>-<job-name>` to the StatefulSet.

For example, with our new `database` role, we have two jobs inside it: `mysql` and `mysql-proxy`. What service should the `database` StatefulSet refer to?
